version: "3.7"

services:
    postgres:
        restart: always
        container_name: test_postgres
        image: postgres:16-alpine
        environment:
          - POSTGRES_DB=postgres
          - POSTGRES_USER=postgres
          - POSTGRES_PASSWORD=postgres
        volumes:
          - ./var/pg_data:/var/lib/postgresql
        ports:
          - "5432:5432"